version: '3'

services:
  mcp-attendance:
    build: ./mcp-attendance
    command: python main.py
    ports:
      - ${MCP_HOST_ATTENDANCE_PORT:-8003}:8000
    volumes:
      - ./mcp-attendance:/app 

  mcp-attendance-static-server:
    image: nginx:1.25.3-alpine
    ports:
      - 8080:80
    volumes:
      - ./train-attendance/data/f_compressed:/usr/share/nginx/html:ro
      - ./train-attendance/default.conf:/etc/nginx/conf.d/default.conf:ro

  mcp-voting:
    build: ./mcp-voting
    command: python main.py
    ports:
      - ${MCP_HOST_VOTING_PORT:-8001}:8000
    volumes:
      - ./mcp-voting:/app

  mcp-budget:
    build: ./mcp-budget
    command: python main.py
    ports:
      - ${MCP_HOST_BUDGET_PORT:-8002}:8000
    volumes:
      - ./mcp-budget:/app

