version: "3"

services:
  nats-server:
    image: nats:2.11.4
    ports:
      - 8222:8222
      - 4222:4222

  ms-gateway:
    build: ./ms-gateway
    ports:
      - ${GATEWAY_PORT:-3000}:3000
    volumes:
      - ./ms-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  ms-documents:
    build: ./ms-documents
    volumes:
      - ./ms-documents/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - POSTGRES_URL=postgresql://postgres:123456@db-documents:5432/documents-app-db

  ms-messages:
    depends_on:
      - db-messages
      - mcp-voting
      - mcp-budget
      - mcp-attendance
    build: ./ms-messages
    ports:
      - ${MESSAGES_PORT:-8000}:8000
    volumes:
      - ./ms-messages/app:/app/app
      - ./ms-messages/alembic:/app/alembic
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PORT=${MESSAGES_PORT:-8000}
      - NATS_SERVERS=${NATS_SERVERS:-nats://nats-server:4222}
      - DB_NAME=${DB_MESSAGES_NAME:-message-app-db}
      - DB_USERNAME=${DB_MESSAGES_USERNAME:-postgres}
      - DB_PASSWORD=${DB_MESSAGES_PASSWORD:-123456}
      - DB_HOST=${DB_MESSAGES_HOST:-db-messages}
      - DB_PORT=${DB_MESSAGES_PORT:-5432}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - MCP_VOTING_URL=http://mcp-voting:8000/mcp
      - MCP_BUDGET_URL=http://mcp-budget:8000/mcp
      - MCP_ATTENDANCE_URL=http://mcp-attendance:8000/mcp

  db-messages:
    container_name: db-messages
    image: postgres:16.2
    restart: always
    volumes:
      - ./others/data/message-app-db/postgres:/var/lib/postgresql/data
      - ./others/data/message-app-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5532:5432
    environment:
      - POSTGRES_DB=${DB_MESSAGES_NAME:-message-app-db}
      - POSTGRES_USER=${DB_MESSAGES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_MESSAGES_PASSWORD:-123456}

  db-documents:
    container_name: db-documents
    image: postgres:16.2
    restart: always
    volumes:
      - ./others/data/documents-app-db/postgres:/var/lib/postgresql/data
      - ./others/data/documents-app-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5732:5432
    environment:
      - POSTGRES_DB=${DB_DOCUMENTS_NAME:-documents-app-db}
      - POSTGRES_USER=${DB_DOCUMENTS_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_DOCUMENTS_PASSWORD:-123456}

  mcp-attendance:
    depends_on:
      - qdrant
    build: ./mcp-attendance
    command: python main.py
    ports:
      - ${MCP_HOST_ATTENDANCE_PORT:-8003}:8000
    volumes:
      - ./mcp-attendance:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

  mcp-voting:
    depends_on:
      - qdrant
    build: ./mcp-voting
    command: python main.py
    ports:
      - ${MCP_HOST_VOTING_PORT:-8001}:8000
    volumes:
      - ./mcp-voting:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

  mcp-budget:
    depends_on:
      - db-budget
    build: ./mcp-budget
    command: python main.py
    ports:
      - ${MCP_HOST_BUDGET_PORT:-8002}:8000
    volumes:
      - ./mcp-budget:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_HOST=${DB_BUDGET_HOST:-db-budget}
      - POSTGRES_PORT=${DB_BUDGET_PORT:-5432}
      - POSTGRES_DB=${DB_BUDGET_NAME:-budget-mcp-db}
      - POSTGRES_USER=${DB_BUDGET_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_BUDGET_PASSWORD:-123456}

  mcp-static-server:
    image: nginx:1.25.3-alpine
    ports:
      - 8080:80
    volumes:
      - ./others/data/nginx-files:/usr/share/nginx/html:ro
      - ./others/data/nginx-files/default.conf:/etc/nginx/conf.d/default.conf:ro

  qdrant:
    image: qdrant/qdrant:v1.14.0
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333 # API REST
      - 6334:6334 # gRPC (opcional)
    volumes:
      - ./others/data/qdrant/storage:/qdrant/storage

  db-budget:
    container_name: db-budget
    image: postgres:16.2
    restart: always
    volumes:
      - ./others/data/budget-mcp-db/postgres:/var/lib/postgresql/data
      - ./others/data/budget-mcp-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5632:5432
    environment:
      - POSTGRES_DB=${DB_MESSAGES_NAME:-budget-mcp-db}
      - POSTGRES_USER=${DB_MESSAGES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_MESSAGES_PASSWORD:-123456}

  frontend:
    build: ./frontend
    ports:
      - 4000:80
    environment:
      - NODE_ENV=production
    depends_on:
      - ms-gateway
