version: '3'

services:
  mcp-voting:
    build: ./mcp-voting
    command: python main.py
    ports:
      - ${MCP_VOTING_PORT:-8001}:8000
    volumes:
      - ./mcp-voting:/app

  mcp-contracting:
    build: ./mcp-contracting
    command: python main.py
    ports:
      - ${MCP_CONTRACTING_PORT:-8002}:8000
    volumes:
      - ./mcp-contracting:/app

  mcp-assistance:
    build: ./mcp-assistance
    command: python main.py
    ports:
      - ${MCP_ASSISTANCE_PORT:-8003}:8000
    volumes:
      - ./mcp-assistance:/app 